### ISSUE TITLE
Phone call

### ISSUE THREAD

**Issue by kaanaksit** [sixfab/Sixfab_RPi_3G-4G-LTE_Base_Shield#1]
Can one make a phone call using Raspberry Pi 4G/LTE Shield Kit? If so is there any examples of that I can look into?

**Comment by saeedjohar** [comment]
Hello, There is no audio codec available on the Base Shield. So you cannot make voice calls. 

But if the scenario is to trigger an event with a call you can use **ATD<number>;** command to do so.

**Comment by kaanaksit** [comment]
Thank you @saeedjohar for letting me know. This resolves the issue.
